### ISSUE TITLE
Updates for UltraLegacy (10_6_X)

### ISSUE THREAD

**Issue by raggleton** [UHH2/UHH2#1520]
Things to be checked/taken care of, especially with respect to the 102X 2016/7/8 differences. I've grouped them by object, since often they are common across years.
Please comment/edit with any missing items!
Some things are only important post-ntupleisation, which have been marked with [analysis]. Everything else is assumed to be important for making ntuples.

PdmV recipe: https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysisSummaryTable

**GENERAL**

Datasets/PPD recommendations UL20 [MiniAODv2](https://docs.google.com/presentation/d/1gEF2jExqS1hWs-dlYgxrTT2xQztYbBZcrLdw45Aiy7g/edit#slide=id.gea94664d3c_0_1) [MiniAODv1](https://docs.google.com/presentation/d/1gEF2jExqS1hWs-dlYgxrTT2xQztYbBZcrLdw45Aiy7g/edit#slide=id.ge8cc301637_0_55)

- [x] propagation of era flag
  - preferred solution: resolve all `import *` and move into generator function --> @hjabusch #1593 
  - alternatively: add explicit statement (encapsulate?) at beginning of each ntuplewriter file
- [x] update CI tests to Summer20 samples --> @mschrode (#1590 #1595)
- [x] update crab production scripts --> @MatthiesC #1587 #1591 
  - [x] storage path
- [x] PUPPI version v15 --> adjust code to not re-cluster with v15 but use directly from MiniAODv2 samples --> @kdeleo, @stalbrec, @abenecke #1592 
- [x] Update to latest --> @jabuschh 
  - CMSSW_10_6_28 [HN](https://hypernews.cern.ch/HyperNews/CMS/get/generators/5153.html) #1589 
  - Global Tags & Eras #1585
- [x] prefiring weights for UL [Twiki recipe](https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1PrefiringWeightRecipe) --> #1568 @MatthiesC 
- [ ] Updated PU reweighting (? )
  - not relevant for the production, PU weights not stored in ntuples
  - [HN](https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/3709/1/1/1/1.html) 
- [ ] Change of SF to JSON format
  - needs (possible) future adaption of code --> probably not ready by all POGs
  - *not relevant for production*, concerns running on ntuples
- [x] Update to higher CMSSW version (needed for egamma reco tools, Puppi v15) --> done in #1572 
- [x] Review list of variables included in the ntuples (based on the histograms being compared during CI): many not filled/not meaningful values @mschrode for MC: [empty](https://github.com/UHH2/UHH2/files/6378615/h_empty.txt), [zero RMS](https://github.com/UHH2/UHH2/files/6378620/h_zerorms.txt), [zero value](https://github.com/UHH2/UHH2/files/6378623/h_zerovalue.txt)
- [x] Why is geninfo.systweights  not filled? @stalbrec problem of an old sample
- [x] Drop support for <= 102X datasets? --> keep for the time being (currently 102X ntuples still used in analysis development, for analyses close to final)

**JETS**

- [x] Fix partonFlavour in jetsAk4Puppi (broken when updatePuppiv14 introduced in #1519 ): related to reclustering at ntupling stage, fixed in PUPPI v15
  - either miniAOD v2, or 
  - update to v15 on the fly 
- [x] AK8CHS/PUPPI PUJetID not stored (jet collection and top collection) --> @apaasch, not defined
- [x] Update list of btaggers - surely some outdated stuff in there? @finnlabe @jabuschh #1581 
- Add new taggers (eg. ParticleNet) @stalbrec
  - [x] ParticleNet added for AK8 jets in #1565 
  - [x] Add mass regression --> @stalbrec 
- GenJets
  - [x] `genjetsAk8Substructure` empty or same value: subjet info empty  → ungroomed AK8 GenJets → no subjets  → use genjetsAk8SubstructureSoftDrop collection instead
  - [x] `slimmedGenJetsAK4/AK8.genparticles_indices empty --> [switches](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/python/ntuple_generator.py#L2506) set to `false` as default
    - m_genparticles_indices holds the indices (integers) of all genparticles related to the genjet
  - [x] `slimmedGenJetsAk8` (works for Ak4) pdgId, hadron/partonFlavour same value --> corresponding jet-parton matching not done ([this condition](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/plugins/NtupleWriter.cc#L1005) always `false`) --> @jabuschh: concerns all AK8 GenJet collections: slimmedGenJetsAK8, genjetsAk8Substructure, genjetsAk8SubstructureSoftDrop
  - pdgid at default value: expected behavior
  - partonFlavour, hadronFlavour at default value  → genjet flavor matching is not working (&gen_jet == aJet always false for AK8 GenJets, [link](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/plugins/NtupleWriter.cc#L1014)), is does work for AK4 → still not really clear unfortunately
  - [x] `slimmedGenJetsAk8` subjet info not available --> @jabuschh: ungroomed AK8 GenJets → no subjets → use genjetsAk8SubstructureSoftDrop collection instead (same as 1.)
- [ ] JME IDs/recommendation --> will be done later, not relevant now @anmalara 
  - JetID [UL recommendations](https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/2121/2.html)
  - JEC/JER recommendations
- [x] Drop btag_info stuff? Not filled / used - potentially adds up a lot (~35 * 0.0038 kB / jet collection, * ~8 collections = 1 kB /event, relative to ~ 9 kB / event MC) --> done with #1544 
- [x] Fix L1Jet_seeds being empty e.g. [validation plot](https://uhh2-integration.web.cern.ch/UHH2integration/test1544/data_UL16postVFP_JetHT_figs/L1Jet_seeds.v4.Pt.pdf) @finnlabe --> expected behaviour, not filled for MC, being updated with imminent PR related to L1 info/objects

**LEPTONS**
- [x] Lepton_keys missing for HOTVR / XCONE #1468 --> @MatthiesC 
  - missing lepton keys: jet-lepton cleaning can only be done via [DeltaR-based cleaning](https://github.com/UHH2/HOTVR/blob/102X_v1/src/HOTVRJetCorrector.cxx#L139) OK for relevant analyses
- [x] Add flag if lepton can be matched to L1 lepton --> @finnlabe @jabuschh #1580 
- [x] Use [EGamma PostRecoTools]( https://twiki.cern.ch/twiki/bin/view/CMS/EgammaPostRecoRecipes) #1571  --> @finnlabe
  - drop support for producing 102X ntuples 2016 and 2017
  - check that we can still run on EOY ntuples all years
  - EGammaID: use consistently tags in ntuples, deprecate on-the-fly ID classes
- [x] Add the latest versions (Tags, IDs, calibrations etc.) for muon/ele and similar recommendations --> @MatthiesC (details see comment below)
- [x] See https://hypernews.cern.ch/HyperNews/CMS/get/muon/1747.html --> @MatthiesC only related to JSON format SF files

**MET**
- [x] Update list of METfilters --> at least one, `BadPFMuonDz` filter only in Summer20 samples --> @jabuschh #1584
  - [status request for recommendations](https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/2113/1/1.html) 
  - [updated ecalBadCalib](https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2)
- [x] `slimmedMETs` filled with 0 --> @abenecke 

**EGAMMA**

- [x] `slimmedPhotonsUSER` zero #1576  --> @jabuschh
  - `m_ptError = 0, m_etaError = 0, m_phiError = 0` --> algo only valid for electrons
  - `m_patParticleIso` commented out, deprecated --> default value

**GENPARTICLES**

- [x] several empty/zero variables  --> @stalbrec
  - `GenParticles.spin` we don't store it (LHE event product not available for every sample)
  - `genInfo.pdf_xPDF1/2` filled (0 in miniAOD) 
- [x] `GenParticles.hadron(parton)Flavour` zero RMS/same value --> @jabuschh `GenParticle` inherits from `FlavourParticle`, which defines fields hadron/partonFlavour

**Comment by MatthiesC** [comment]
@anmalara & AlexP: I noticed that you work on prefiring weights for UL. This should be added here on the list as well, correct?

**Comment by mschrode** [comment]
Yes, please add yourself to any of the items if you are working on them (or intend to)

**Comment by stalbrec** [comment]
Hi, i had a look into the issue regarding the filling of `genInfo.systweights`. 
I have not seen any apparent problem when processing Summer19/Summer20 UL MINIAODSIM files, i.e. `systweights` seem to be filled (i tested both a madgraph and powheg sample - i can check other sample if you like)

However, I remembered that there was a problem with RelVal samples during UL validation, so I also checked a UL18 RelVal sample (`/RelValQCD_FlatPt_15_3000HS_13_UP18/CMSSW_10_6_4_patch1-PU25ns_106X_upgrade2018_realistic_v9_HS_resub-v1/MINIAODSIM`) and here `systweights` in the Ntuple is empty.  
So I guess the `LHEEventProduct` just does not exist for RelVals?

Has anyone else seen any other issue with `genInfo.systweights`, or was this the problem the issue refers to?

**Comment by MatthiesC** [comment]
I've had a look into the lepton IDs and, to my understanding, everything is in place:

- For electrons (and photons), the recommendation for all UL years is to use the "Fall17V2" IDs derived in 94X (cut-based and MVA), see [1], [2], and [2a]. The electron IDs are implemented on analysis-level, see [3].
- For muons, the IDs are also the same for UL as for 2016v3, 2017v2, and 2018; for details, see [4] and [5]. The muon IDs are implemented on ntuplewriter-level, not analysis-level, see [6].

Scale factors:

- The muon ID and ISO scale factors are available in [7]. I already added them some time ago, see [8].
- The EGamma scale factor root files are available in [9]. Since there are so many root files, I think it is the best that everyone downloads the ones s*he needs h{im,er}self.

[1] https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
[2] https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2
[2a] https://twiki.cern.ch/twiki/bin/view/CMS/MultivariatePhotonIdentificationRun2
[3] https://github.com/UHH2/UHH2/blob/RunII_106X_v1/common/include/ElectronIds.h
[4] https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonSelection
[5] https://twiki.cern.ch/twiki/bin/view/CMS/MuonUL201{6,7,8} (choose a year)
[6] https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/plugins/NtupleWriterLeptons.cxx#L275-L298
[7] https://twiki.cern.ch/twiki/bin/view/CMS/MuonReferenceEffsRun2Legacy
[8] https://github.com/UHH2/UHH2/commit/5fc7a0784f16f367f2eaa5cc50afc1d8821196ac
[9] https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018

**Comment by MatthiesC** [comment]
> 
> 
> @anmalara & AlexP: I noticed that you work on prefiring weights for UL. This should be added here on the list as well, correct?

@mschrode Could you add "prefiring weights for UL17 and UL16" as an item under "general", please? Afaik, for UL18 there are no prefiring weights necessary.
Twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe

**Comment by mschrode** [comment]
Thanks @MatthiesC , done! (Yes, for 2018, there are no prefiring corrections needed as the effect was fixed.)
